# Generated by Django 2.2.6 on 2020-01-12 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('c_id', models.IntegerField(primary_key=True, serialize=False)),
                ('c_code', models.CharField(blank=True, max_length=100, null=True)),
                ('c_name', models.CharField(blank=True, max_length=100, null=True)),
                ('i_code', models.CharField(blank=True, max_length=100, null=True)),
                ('i_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('p_id', models.IntegerField(primary_key=True, serialize=False)),
                ('p_name', models.CharField(blank=True, max_length=45, null=True)),
                ('img_src', models.URLField(unique=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('link', models.URLField(unique=True)),
                ('c', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='DKEA.Category')),
            ],
        ),
    ]
